version = "3.9.8"
runner.dialect = scala213
maxColumn = 100
assumeStandardLibraryStripMargin = true
align.preset = none
danglingParentheses.preset = false
docstrings.style = Asterisk
newlines.source = keep
runner.optimizer.maxVisitsPerToken = 20000
